export const educationWordPacks = [
  {
    "level": "SFI",
    "notebook": "SFI 常用词",
    "words": [
      {
        "id": "word_0abaeabc98ef013c",
        "swedish": "bo",
        "pos": "verb",
        "pos_detail": "vi",
        "chinese": "居住；住在某处。",
        "english": "Att leva eller ha sitt hem på en plats.",
        "forms": "imperativ: bo; infinitiv: bo; presens: bor; preteritum: bodde; supinum: bott",
        "example": "Jag bor i Malmö med min familj.",
        "collocations": "bo i en lägenhet | 住在公寓里 | Jag bor i en lägenhet på tredje våningen.\nbo nära centrum | 住在市中心附近 | Vi bor nära centrum.\nbo tillsammans | 共同居住 | De bor tillsammans.\nbo med sin familj | 和家人住在一起 | Hon bor med sin familj.\nbo hos någon | 住在某人家里 | Han bor hos sin syster.",
        "related_words": "bostad | 住房\nhem | 家\nflytta | 搬家",
        "favorite": false,
        "learned": false,
        "review_count": 0,
        "wrong_count": 0,
        "last_reviewed": null,
        "next_review_at": null,
        "created_at": null,
        "updated_at": null,
        "tags": [
          "SFI 生活"
        ]
      },
      {
        "id": "word_4cbe85a6770e10b0",
        "swedish": "arbeta",
        "pos": "verb",
        "pos_detail": "vi",
        "chinese": "工作；上班。",
        "english": "Att ha ett jobb eller göra ett arbete.",
        "forms": "imperativ: arbeta; infinitiv: arbeta; presens: arbetar; preteritum: arbetade; supinum: arbetat",
        "example": "Hon arbetar på ett äldreboende.",
        "collocations": "arbeta heltid | 全职工作 | Hon arbetar heltid.\narbeta deltid | 兼职工作 | Jag arbetar deltid nu.\narbeta som undersköterska | 作为护理助理工作 | Han arbetar som undersköterska.\narbeta på ett äldreboende | 在养老院工作 | Hon arbetar på ett äldreboende.\narbeta hemifrån | 在家工作 | Många arbetar hemifrån.",
        "related_words": "jobb | 工作\narbete | 工作\nyrke | 职业",
        "favorite": false,
        "learned": false,
        "review_count": 0,
        "wrong_count": 0,
        "last_reviewed": null,
        "next_review_at": null,
        "created_at": null,
        "updated_at": null,
        "tags": [
          "SFI 工作"
        ]
      },
      {
        "id": "word_2a97424d7beec8ef",
        "swedish": "söka",
        "pos": "verb",
        "pos_detail": "vt",
        "chinese": "寻找；申请。",
        "english": "Att leta efter något eller ansöka om något.",
        "forms": "imperativ: sök; infinitiv: söka; presens: söker; preteritum: sökte; supinum: sökt",
        "example": "Jag söker jobb i kommunen.",
        "collocations": "söka jobb | 申请工作；找工作 | Hon söker jobb i kommunen.\nsöka bostad | 申请住房；找房子 | De söker bostad i stan.\nsöka information | 寻找信息；查询资料 | Jag söker information på nätet.\nsöka till utbildning | 申请学习项目；报考 | Han ska söka till gymnasiet.",
        "related_words": "leta | 寻找\nansöka | 申请\nhitta | 找到",
        "favorite": false,
        "learned": false,
        "review_count": 0,
        "wrong_count": 0,
        "last_reviewed": null,
        "next_review_at": null,
        "created_at": null,
        "updated_at": null,
        "tags": [
          "SFI 社会"
        ]
      },
      {
        "id": "word_8f8b460a42501d73",
        "swedish": "ringa",
        "pos": "verb",
        "pos_detail": "vt/vi",
        "chinese": "打电话；响起，发出铃声。常用于日常瑞典语里“给某人打电话”或“电话/铃声响”。注意：作“响”时，多见于电话、铃声、警报等，不太常用于一般物体的自然发声。",
        "english": "telefonera; låta, särskilt om telefon, klocka eller signal",
        "forms": "imperativ: ring; infinitiv: ringa; presens: ringer; preteritum: ringde; supinum: ringt",
        "example": "Kan du ringa vårdcentralen i morgon?\nTelefonen ringer hela tiden.",
        "collocations": "ringa tillbaka | 回电话；再打过去 | Jag ringer tillbaka senare.\nringa någon | 给某人打电话 | Jag ringer dig i kväll.\nringa upp | 回拨电话；打回去 | Kan du ringa upp mig senare?\nringa till skolan | 打电话到学校 | Vi måste ringa till skolan i dag.\ntelefonen ringer | 电话响 | Telefonen ringer hela tiden.",
        "related_words": "telefonera | 打电话，较正式的动词\nsamtal | 电话、谈话；ett samtal 可指一次通话\ntelefon | 电话；也可指手机或电话设备\nringa upp | 给某人回拨/拨通电话\nsvara | 接电话、回答",
        "favorite": false,
        "learned": false,
        "review_count": 0,
        "wrong_count": 0,
        "last_reviewed": null,
        "next_review_at": null,
        "created_at": null,
        "updated_at": null,
        "tags": [
          "SFI 日常"
        ]
      },
      {
        "id": "word_94b7f34c03679051",
        "swedish": "boka",
        "pos": "verb",
        "pos_detail": "vt",
        "chinese": "预订；预约。",
        "english": "Att beställa eller bestämma en tid i förväg.",
        "forms": "imperativ: boka; infinitiv: boka; presens: bokar; preteritum: bokade; supinum: bokat",
        "example": "Jag behöver boka en tid hos tandläkaren.",
        "collocations": "boka tid | 预约时间 | Jag måste boka tid hos tandläkaren.\nboka biljett | 预订票；买票 | Vi bokar biljett online.\nboka om tiden | 改约时间；重新预约 | Jag behöver boka om tiden.\nboka ett besök | 预约一次访问/就诊 | Hon vill boka ett besök.",
        "related_words": "beställa | 订购\nreservation | 预订\nbiljett | 票",
        "favorite": false,
        "learned": false,
        "review_count": 0,
        "wrong_count": 0,
        "last_reviewed": null,
        "next_review_at": null,
        "created_at": null,
        "updated_at": null,
        "tags": [
          "SFI 医疗"
        ]
      },
      {
        "id": "word_f3608e140ac30fce",
        "swedish": "förstå",
        "pos": "verb",
        "pos_detail": "vt",
        "chinese": "理解；听懂。",
        "english": "Att veta vad något betyder eller att fatta.",
        "forms": "imperativ: förstå; infinitiv: förstå; presens: förstår; preteritum: förstod; supinum: förstått",
        "example": "Jag förstår inte frågan.",
        "collocations": "förstå svenska | 听懂/理解瑞典语 | Jag förstår lite svenska.\nförstå vad någon menar | 理解某人的意思 | Nu förstår jag vad du menar.\nsvårt att förstå | 难以理解 | Texten är svår att förstå.\nförstå frågan | 听懂问题；理解问题 | Jag förstår inte frågan.",
        "related_words": "begripa | 理解；懂得（动词）\nförståelse | 理解；领会（名词）\nuppfatta | 听懂；察觉（动词）\ntolka | 解释；领会（动词）\nmissförstå | 误解；听错（动词）",
        "favorite": false,
        "learned": false,
        "review_count": 0,
        "wrong_count": 0,
        "last_reviewed": null,
        "next_review_at": null,
        "created_at": null,
        "updated_at": null,
        "tags": [
          "SFI 学习"
        ]
      },
      {
        "id": "word_2c31c6b30e43b07a",
        "swedish": "behöva",
        "pos": "verb",
        "pos_detail": "vt",
        "chinese": "需要；必须。",
        "english": "Att ha nytta av något eller vara tvungen att ha det.",
        "forms": "imperativ: behöv; infinitiv: behöva; presens: behöver; preteritum: behövde; supinum: behövt",
        "example": "Jag behöver hjälp med blanketten.",
        "collocations": "behöva hjälp | 需要帮助 | Jag behöver hjälp med blanketten.\nbehöva gå | 需要走；得离开 | Jag behöver gå nu.\nbehöver inte | 不需要；不必 | Du behöver inte betala nu.\nbehöva tid | 需要时间 | Jag behöver mer tid.",
        "related_words": "måste | 必须\nvilja | 想要\nköpa | 买",
        "favorite": false,
        "learned": false,
        "review_count": 0,
        "wrong_count": 0,
        "last_reviewed": null,
        "next_review_at": null,
        "created_at": null,
        "updated_at": null,
        "tags": [
          "SFI 日常"
        ]
      },
      {
        "id": "word_e103412316075294",
        "swedish": "betala",
        "pos": "verb",
        "pos_detail": "vt/vi",
        "chinese": "付款；支付。",
        "english": "Att ge pengar för något.",
        "forms": "imperativ: betala; infinitiv: betala; presens: betalar; preteritum: betalade; supinum: betalat",
        "example": "Du kan betala med Swish.",
        "collocations": "betala räkningar | 付账单 | Jag betalar räkningarna i dag.\nbetala med kort | 用卡支付 | Du kan betala med kort.\nbetala hyran | 交房租 | Hon betalar hyran varje månad.\nbetala kontant | 付现金 | Kan jag betala kontant?",
        "related_words": "kort | 卡\nkontanter | 现金\nkvitto | 收据",
        "favorite": false,
        "learned": false,
        "review_count": 0,
        "wrong_count": 0,
        "last_reviewed": null,
        "next_review_at": null,
        "created_at": null,
        "updated_at": null,
        "tags": [
          "SFI 经济"
        ]
      },
      {
        "id": "word_df14635cd8f22120",
        "swedish": "en tid",
        "pos": "noun",
        "pos_detail": "en",
        "chinese": "时间；预约时间。",
        "english": "En bestämd stund eller en bokad tid.",
        "forms": "en tid; tiden; tider; tiderna",
        "example": "Jag har en tid på vårdcentralen klockan tio.",
        "collocations": "boka en tid | 预约一个时间 | Jag vill boka en tid.\npassa tiden | 准时；赶上时间 | Du måste passa tiden.\nkomma i tid | 准时到达 | Hon kommer alltid i tid.\nen ledig tid | 空闲时间；可预约的时间 | Jag har en ledig tid på fredag.",
        "related_words": "tid | 时间；时候（名词）\npunktlighet | 守时；准时（名词）\nledig tid | 空闲时间；可预约时间（短语）\nbeställa tid | 预约时间（短语）\nkomma i tid | 准时到达（短语）",
        "favorite": false,
        "learned": false,
        "review_count": 0,
        "wrong_count": 0,
        "last_reviewed": null,
        "next_review_at": null,
        "created_at": null,
        "updated_at": null,
        "tags": [
          "SFI 医疗"
        ]
      },
      {
        "id": "word_2ce940dda3f08471",
        "swedish": "ett personnummer",
        "pos": "noun",
        "pos_detail": "ett",
        "chinese": "个人身份号码；瑞典社会常用身份号码。",
        "english": "Ett nummer som visar vem du är i Sverige.",
        "forms": "ett personnummer; personnumret; personnummer; personnumren",
        "example": "Skriv ditt personnummer här.",
        "collocations": "ange personnummer | 填写个人号码 | Ange ditt personnummer här.\nsvenskt personnummer | 瑞典个人号码 | Han har ett svenskt personnummer.\nde fyra sista siffrorna | 后四位数字 | Jag minns bara de fyra sista siffrorna.\nkontrollera personnummer | 核对个人号码 | Vi måste kontrollera personnumret.",
        "related_words": "identitetsnummer | 身份号码（名词）\nnummer | 号码（名词）\nfyra sista siffrorna | 后四位数字（短语）\nkontrollera | 核对；检查（动词）\nsvenskt id | 瑞典身份证明（短语）",
        "favorite": false,
        "learned": false,
        "review_count": 0,
        "wrong_count": 0,
        "last_reviewed": null,
        "next_review_at": null,
        "created_at": null,
        "updated_at": null,
        "tags": [
          "SFI 社会"
        ]
      },
      {
        "id": "word_2f21d835e4675430",
        "swedish": "en ansökan",
        "pos": "noun",
        "pos_detail": "en",
        "chinese": "申请；申请表。",
        "english": "En begäran om något, ofta på papper eller digitalt.",
        "forms": "en ansökan; ansökan; ansökningar; ansökningarna",
        "example": "Jag skickade min ansökan i fredags.",
        "collocations": "lämna in en ansökan | 递交申请 | Jag ska lämna in en ansökan.\nfylla i ansökan | 填写申请表 | Du måste fylla i ansökan.\nansökan om bostad | 住房申请 | Hon har skickat en ansökan om bostad.\nbesluta om ansökan | 决定申请结果 | Myndigheten ska besluta om ansökan.",
        "related_words": "ansöka | 申请（动词）\nansökningsblankett | 申请表（名词）\nlämna in | 递交；提交（动词短语）\nansökningsfrist | 申请截止时间（名词）\nbegäran | 请求；申请（名词）",
        "favorite": false,
        "learned": false,
        "review_count": 0,
        "wrong_count": 0,
        "last_reviewed": null,
        "next_review_at": null,
        "created_at": null,
        "updated_at": null,
        "tags": [
          "SFI 社会"
        ]
      },
      {
        "id": "word_4871735bf28aa829",
        "swedish": "en hyra",
        "pos": "noun",
        "pos_detail": "en",
        "chinese": "房租；租金。",
        "english": "Rent.",
        "forms": "en hyra; hyran; hyror; hyrorna",
        "example": "Hyran ska betalas i slutet av månaden.",
        "collocations": "betala hyran | 交房租 | Hyran ska betalas i dag.\nhög hyra | 高房租 | Det är hög hyra här.\nhyran ingår | 房租包含在内 | Elen ingår inte, men hyran ingår.\nsänka hyran | 降低房租 | De vill sänka hyran.",
        "related_words": "hyran | 房租；租金（名词）\nhyresvärd | 房东（名词）\nhyresgäst | 租客（名词）\nboende | 住房；居住（名词）\navgift | 费用；收费（名词）",
        "favorite": false,
        "learned": false,
        "review_count": 0,
        "wrong_count": 0,
        "last_reviewed": null,
        "next_review_at": null,
        "created_at": null,
        "updated_at": null,
        "tags": [
          "SFI 住房"
        ]
      },
      {
        "id": "word_d8701c7c47ac074f",
        "swedish": "ett kvitto",
        "pos": "noun",
        "pos_detail": "ett",
        "chinese": "收据；小票。",
        "english": "Ett bevis på att du har betalat.",
        "forms": "ett kvitto; kvittot; kvitton; kvittona",
        "example": "Vill du ha kvittot?",
        "collocations": "spara kvittot | 保留收据 | Spara kvittot ifall du behöver det.\ndigitalt kvitto | 电子收据 | Jag fick ett digitalt kvitto.\nfå ett kvitto | 得到收据 | Kan jag få ett kvitto?\nvisa kvittot | 出示收据 | Visa kvittot i kassan.",
        "related_words": "faktura | 发票；账单（名词）\nbevis | 证明；凭证（名词）\nspara | 保存；保留（动词）\nvisa upp | 出示（动词短语）\ndigitalt kvitto | 电子收据（短语）",
        "favorite": false,
        "learned": false,
        "review_count": 0,
        "wrong_count": 0,
        "last_reviewed": null,
        "next_review_at": null,
        "created_at": null,
        "updated_at": null,
        "tags": [
          "SFI 购物"
        ]
      },
      {
        "id": "word_804f8568a01fb89c",
        "swedish": "sjuk",
        "pos": "adjective",
        "pos_detail": "adj.",
        "chinese": "生病的；不舒服的。",
        "english": "När man inte mår bra i kroppen eller är frisk.",
        "forms": "en: sjuk; ett: sjukt; plural: sjuka",
        "example": "Min son är sjuk idag.",
        "collocations": "vara sjuk | 生病；患病 | Jag är sjuk idag.\nsjukanmäla sig | 报病；请病假 | Hon sjukanmälde sig i morse.\nsjuk i feber | 发烧生病 | Barnet är sjuk i feber.\nvara sjukskriven | 休病假 | Han är sjukskriven denna vecka.",
        "related_words": "frisk | 健康的\nförkyld | 感冒的\nvila | 休息",
        "favorite": false,
        "learned": false,
        "review_count": 0,
        "wrong_count": 0,
        "last_reviewed": null,
        "next_review_at": null,
        "created_at": null,
        "updated_at": null,
        "tags": [
          "SFI 医疗"
        ]
      },
      {
        "id": "word_db956bea628fcebb",
        "swedish": "ledig",
        "pos": "adjective",
        "pos_detail": "adj.",
        "chinese": "空闲的；休假的；可用的。",
        "english": "När man inte arbetar eller har tid.",
        "forms": "en: ledig; ett: ledigt; plural: lediga",
        "example": "Är du ledig på lördag?",
        "collocations": "vara ledig | 休息；有空 | Jag är ledig på fredag.\nledig tid | 空闲时间 | Jag har ledig tid efter lunch.\nledig lägenhet | 空房；待租公寓 | Det finns en ledig lägenhet här.\nvara ledig från jobbet | 放假；不工作 | Hon är ledig från jobbet i dag.",
        "related_words": "fri | 空闲的\nsemester | 假期\nupptagen | 忙的",
        "favorite": false,
        "learned": false,
        "review_count": 0,
        "wrong_count": 0,
        "last_reviewed": null,
        "next_review_at": null,
        "created_at": null,
        "updated_at": null,
        "tags": [
          "SFI 日常"
        ]
      },
      {
        "id": "word_9f79ececb67a0fd9",
        "swedish": "vanlig",
        "pos": "adjective",
        "pos_detail": "adj.",
        "chinese": "普通的；常见的。",
        "english": "Något som ofta händer eller är normalt.",
        "forms": "en: vanlig; ett: vanligt; plural: vanliga",
        "example": "Det är en vanlig fråga på SFI.",
        "collocations": "vanligt namn | 常见的名字 | Anna är ett vanligt namn.\nvanlig mat | 普通的食物；家常菜 | Vi äter vanlig mat hemma.\nsom vanligt | 和往常一样 | Jag går till jobbet som vanligt.\nvanlig fråga | 常见问题 | Det är en vanlig fråga.",
        "related_words": "normal | 正常的\nofta | 经常\novanlig | 不常见的",
        "favorite": false,
        "learned": false,
        "review_count": 0,
        "wrong_count": 0,
        "last_reviewed": null,
        "next_review_at": null,
        "created_at": null,
        "updated_at": null,
        "tags": [
          "SFI 常用"
        ]
      },
      {
        "id": "word_083d8aaa090ad086",
        "swedish": "ofta",
        "pos": "adverb",
        "pos_detail": "adv.",
        "chinese": "经常。",
        "english": "Often.",
        "forms": "ofta",
        "example": "Jag tränar ofta efter skolan.",
        "collocations": "ganska ofta | 相当经常 | Jag tränar ganska ofta.\nhur ofta | 多久一次；多常 | Hur ofta går du till gymmet?\nofta på morgonen | 经常在早上 | Hon pluggar ofta på morgonen.\nofta tillsammans | 经常一起 | De ses ofta tillsammans.",
        "related_words": "vanligtvis | 通常（副词）\nregelbundet | 定期地；有规律地（副词）\nibland | 有时（副词）\nsällan | 很少（副词）\nalltid | 总是（副词）",
        "favorite": false,
        "learned": false,
        "review_count": 0,
        "wrong_count": 0,
        "last_reviewed": null,
        "next_review_at": null,
        "created_at": null,
        "updated_at": null,
        "tags": [
          "SFI 时间"
        ]
      },
      {
        "id": "word_b6dbe6f2c16fe63c",
        "swedish": "ibland",
        "pos": "adverb",
        "pos_detail": "adv.",
        "chinese": "有时候。",
        "english": "Sometimes.",
        "forms": "ibland",
        "example": "Ibland tar jag bussen till jobbet.",
        "collocations": "ibland på helgen | 有时在周末 | Vi reser ibland på helgen.\nibland hemma | 有时在家 | Jag jobbar ibland hemma.\nibland svårt | 有时很难 | Det är ibland svårt att förstå.\nibland på kvällen | 有时在晚上 | Hon läser ibland på kvällen.",
        "related_words": "ofta | 经常（副词）\nsällan | 很少（副词）\nvanligtvis | 通常（副词）\nmer sällan | 更少地；较少（短语）\nibland och ibland | 有时……有时……（短语）",
        "favorite": false,
        "learned": false,
        "review_count": 0,
        "wrong_count": 0,
        "last_reviewed": null,
        "next_review_at": null,
        "created_at": null,
        "updated_at": null,
        "tags": [
          "SFI 时间"
        ]
      },
      {
        "id": "word_fefce30d062db339",
        "swedish": "eftersom",
        "pos": "phrase",
        "pos_detail": "连词",
        "chinese": "因为；由于。",
        "english": "Används för att förklara varför något händer.",
        "forms": "eftersom",
        "example": "Jag stannar hemma eftersom jag är sjuk.",
        "collocations": "eftersom att | 因为；由于（口语/非正式） | Jag stannar hemma eftersom att jag är sjuk.\neftersom jag | 因为我…… | Jag gick hem eftersom jag var trött.\neftersom det | 因为那/因为这 | Jag kommer sent eftersom det regnar.\neftersom du | 因为你…… | Jag frågar eftersom du vet mer.",
        "related_words": "för att | 为了；因为（连词/短语）\norsaken är att | 原因是（短语）\ndärför att | 因为（连词/短语）\norsak | 原因（名词）\nförklara | 解释；说明（动词）",
        "favorite": false,
        "learned": false,
        "review_count": 0,
        "wrong_count": 0,
        "last_reviewed": null,
        "next_review_at": null,
        "created_at": null,
        "updated_at": null,
        "tags": [
          "SFI 连接词"
        ]
      },
      {
        "id": "word_207726c25d8ac7d0",
        "swedish": "i stället",
        "pos": "phrase",
        "pos_detail": "固定表达",
        "chinese": "改为；代替；而是。",
        "english": "Instead.",
        "forms": "i stället",
        "example": "Vi tar tåget i stället för bilen.",
        "collocations": "i stället för | 代替；而不是 | Vi tar tåget i stället för bilen.\ngöra något i stället | 改做别的；代替去做 | Jag stannar hemma och vilar i stället.\nta en annan tid i stället | 改约别的时间 | Vi kan ta en annan tid i stället.\nköpa kaffe i stället | 改买咖啡 | Jag köper te i stället.",
        "related_words": "istället för | 代替；而不是（短语）\nbyta ut | 替换；更换（动词短语）\nersätta | 代替；取代（动词）\nalternativ | 选择；替代方案（名词）\nå andra sidan | 另一方面（短语）",
        "favorite": false,
        "learned": false,
        "review_count": 0,
        "wrong_count": 0,
        "last_reviewed": null,
        "next_review_at": null,
        "created_at": null,
        "updated_at": null,
        "tags": [
          "SFI 口语"
        ]
      }
    ]
  },
  {
    "level": "SVA grundläggande",
    "notebook": "SVA Grund 常用词",
    "words": [
      {
        "id": "word_475b1b61fb04f280",
        "swedish": "påverka",
        "pos": "verb",
        "pos_detail": "vt",
        "chinese": "影响；对某人或某事产生作用。",
        "english": "Att förändra något eller ha betydelse för något.",
        "forms": "imperativ: påverka; infinitiv: påverka; presens: påverkar; preteritum: påverkade; supinum: påverkat",
        "example": "Stress kan påverka sömnen.",
        "collocations": "påverka hälsan | 影响健康 | Stress kan påverka hälsan.\npåverka beslutet | 影响决定 | Det kan påverka beslutet.\npåverkas av vädret | 受天气影响 | Jag påverkas av vädret.\npåverka ekonomin | 影响经济 | Priserna påverkar ekonomin.",
        "related_words": "effekt | 效果\ninverka | 影响\nförändra | 改变",
        "favorite": false,
        "learned": false,
        "review_count": 0,
        "wrong_count": 0,
        "last_reviewed": null,
        "next_review_at": null,
        "created_at": null,
        "updated_at": null,
        "tags": [
          "SVA Grund 学术"
        ]
      },
      {
        "id": "word_dd28a1b39275750d",
        "swedish": "utveckla",
        "pos": "verb",
        "pos_detail": "vt",
        "chinese": "发展；展开；进一步说明。",
        "english": "Att göra något bättre eller mer avancerat.",
        "forms": "imperativ: utveckla; infinitiv: utveckla; presens: utvecklar; preteritum: utvecklade; supinum: utvecklat",
        "example": "Kan du utveckla ditt svar lite mer?",
        "collocations": "utveckla språket | 发展/提高语言能力 | Barnet utvecklar språket snabbt.\nutveckla en idé | 发展一个想法 | Vi ska utveckla en idé.\nutvecklas snabbt | 发展很快 | Företaget utvecklas snabbt.\nutveckla svaret | 进一步展开答案 | Kan du utveckla svaret?",
        "related_words": "växa | 增长\nskapa | 创建\nförbättra | 改进",
        "favorite": false,
        "learned": false,
        "review_count": 0,
        "wrong_count": 0,
        "last_reviewed": null,
        "next_review_at": null,
        "created_at": null,
        "updated_at": null,
        "tags": [
          "SVA Grund 写作"
        ]
      },
      {
        "id": "word_f093269e4cd3e294",
        "swedish": "jämföra",
        "pos": "verb",
        "pos_detail": "vt",
        "chinese": "比较。",
        "english": "Att se likheter och skillnader mellan saker.",
        "forms": "imperativ: jämför; infinitiv: jämföra; presens: jämför; preteritum: jämförde; supinum: jämfört",
        "example": "Jämför texterna och hitta likheter.",
        "collocations": "jämföra med | 与……比较 | Jämför med ditt eget svar.\njämföra priser | 比较价格 | Jag jämför priser på nätet.\njämföra två texter | 比较两篇文章 | Vi ska jämföra två texter.\njämföra alternativ | 比较选择 | Det är bra att jämföra alternativen.",
        "related_words": "pris | 价格\nkvalitet | 质量\nskillnad | 差别",
        "favorite": false,
        "learned": false,
        "review_count": 0,
        "wrong_count": 0,
        "last_reviewed": null,
        "next_review_at": null,
        "created_at": null,
        "updated_at": null,
        "tags": [
          "SVA Grund 阅读"
        ]
      },
      {
        "id": "word_117f1652671f5a9c",
        "swedish": "förklara",
        "pos": "verb",
        "pos_detail": "vt",
        "chinese": "解释；说明。",
        "english": "Att berätta så att någon förstår.",
        "forms": "imperativ: förklara; infinitiv: förklara; presens: förklarar; preteritum: förklarade; supinum: förklarat",
        "example": "Läraren förklarar ordet med ett exempel.",
        "collocations": "förklara varför | 解释为什么 | Kan du förklara varför?\nförklara skillnaden | 解释区别 | Läraren förklarar skillnaden.\nförklara för någon | 向某人解释 | Hon förklarar för mig.\nförklara med exempel | 用例子解释 | Förklara med ett exempel.",
        "related_words": "betyda | 意味着\nförstå | 理解\nbegrepp | 概念",
        "favorite": false,
        "learned": false,
        "review_count": 0,
        "wrong_count": 0,
        "last_reviewed": null,
        "next_review_at": null,
        "created_at": null,
        "updated_at": null,
        "tags": [
          "SVA Grund 学习"
        ]
      },
      {
        "id": "word_ae033a49f7b512e9",
        "swedish": "beskriva",
        "pos": "verb",
        "pos_detail": "vt",
        "chinese": "描述；描写。",
        "english": "Att berätta hur något ser ut eller är.",
        "forms": "imperativ: beskriv; infinitiv: beskriva; presens: beskriver; preteritum: beskrev; supinum: beskrivit",
        "example": "Beskriv personen på bilden.",
        "collocations": "beskriva känslor | 描述感受 | Du kan beskriva känslorna.\nbeskriva en situation | 描述一种情况 | Beskriv situationen kort.\nkort beskriva | 简短描述 | Kan du kort beskriva ditt arbete?\nbeskriva personen | 描述这个人 | Beskriv personen på bilden.",
        "related_words": "förklara | 解释\nsäga | 说\nadjektiv | 形容词",
        "favorite": false,
        "learned": false,
        "review_count": 0,
        "wrong_count": 0,
        "last_reviewed": null,
        "next_review_at": null,
        "created_at": null,
        "updated_at": null,
        "tags": [
          "SVA Grund 写作"
        ]
      },
      {
        "id": "word_c163d95267d485e8",
        "swedish": "handla om",
        "pos": "verb",
        "pos_detail": "vi + prep.",
        "chinese": "关于；讲的是。",
        "english": "Att vara om något, att något har som ämne.",
        "forms": "imperativ: handla om; infinitiv: handla om; presens: handlar om; preteritum: handlade om; supinum: handlat om",
        "example": "Texten handlar om arbete och integration.",
        "collocations": "handla om samhället | 讲述社会；关于社会 | Texten handlar om samhället.\nvad handlar det om | 讲的是什么；内容是什么 | Vad handlar det om?\nboken handlar om | 这本书讲的是 | Boken handlar om kärlek.\nhandla om arbete | 关于工作 | Filmen handlar om arbete.",
        "related_words": "vara om | 是关于；涉及（动词短语）\nägna sig åt | 从事；专注于（动词短语）\nämne | 主题；话题（名词）\ninnehåll | 内容（名词）\nberätta om | 讲述关于（动词短语）",
        "favorite": false,
        "learned": false,
        "review_count": 0,
        "wrong_count": 0,
        "last_reviewed": null,
        "next_review_at": null,
        "created_at": null,
        "updated_at": null,
        "tags": [
          "SVA Grund 阅读"
        ]
      },
      {
        "id": "word_84bbedc4b800f043",
        "swedish": "ett samhälle",
        "pos": "noun",
        "pos_detail": "ett",
        "chinese": "社会；社区。",
        "english": "Människor och livet tillsammans på en plats eller i ett land.",
        "forms": "ett samhälle; samhället; samhällen; samhällena",
        "example": "Skolan är en viktig del av samhället.",
        "collocations": "svenska samhället | 瑞典社会 | Hon lär sig om det svenska samhället.\nett demokratiskt samhälle | 民主社会 | Vi lever i ett demokratiskt samhälle.\nsamhällets regler | 社会规则 | Samhällets regler är viktiga.\npåverka samhället | 影响社会 | Ungas val kan påverka samhället.",
        "related_words": "stat | 国家；强调国家机构和治理。\nkommun | 市镇；地方行政单位。\ngemenskap | 共同体、归属感；强调人与人之间的联系。\nmedborgare | 公民；社会中的成员。",
        "favorite": false,
        "learned": false,
        "review_count": 0,
        "wrong_count": 0,
        "last_reviewed": null,
        "next_review_at": null,
        "created_at": null,
        "updated_at": null,
        "tags": [
          "SVA Grund 社会"
        ]
      },
      {
        "id": "word_cee0823234510823",
        "swedish": "en erfarenhet",
        "pos": "noun",
        "pos_detail": "en",
        "chinese": "经验；经历。",
        "english": "Experience.",
        "forms": "en erfarenhet; erfarenheten; erfarenheter; erfarenheterna",
        "example": "Hon har lång erfarenhet av service.",
        "collocations": "tidigare erfarenhet | 之前的经验 | Hon har tidigare erfarenhet.\ndela erfarenheter | 分享经验 | Vi kan dela erfarenheter.\nerfarenhet av arbete | 工作经验 | Han har erfarenhet av arbete i butik.\nlång erfarenhet | 丰富经验 | De har lång erfarenhet.",
        "related_words": "erfaren | 有经验的（形容词）\nerfarenhet av | ……方面的经验（短语）\nkunskap | 知识；了解（名词）\npraktik | 实习；实践（名词）\nutbildning | 教育；培训（名词）",
        "favorite": false,
        "learned": false,
        "review_count": 0,
        "wrong_count": 0,
        "last_reviewed": null,
        "next_review_at": null,
        "created_at": null,
        "updated_at": null,
        "tags": [
          "SVA Grund 工作"
        ]
      },
      {
        "id": "word_d28dc4cd6007908e",
        "swedish": "ett ansvar",
        "pos": "noun",
        "pos_detail": "ett",
        "chinese": "责任。",
        "english": "Responsibility.",
        "forms": "ett ansvar; ansvaret; ansvar; ansvaren",
        "example": "Alla har ansvar för arbetsmiljön.",
        "collocations": "ta ansvar | 承担责任 | Du måste ta ansvar.\nha ansvar för | 对……负责 | Hon har ansvar för barnen.\neget ansvar | 自己的责任 | Det är ditt eget ansvar.\ndela ansvar | 分担责任 | Vi delar ansvar hemma.",
        "related_words": "skyldighet | 义务；更强调必须做。\nroll | 角色；与责任有关。\nplikt | 义务、责任；较正式。\nomsorg | 照顾、关怀；责任的一部分。",
        "favorite": false,
        "learned": false,
        "review_count": 0,
        "wrong_count": 0,
        "last_reviewed": null,
        "next_review_at": null,
        "created_at": null,
        "updated_at": null,
        "tags": [
          "SVA Grund 社会"
        ]
      },
      {
        "id": "word_9001d4d93b4ae5b2",
        "swedish": "en möjlighet",
        "pos": "noun",
        "pos_detail": "en",
        "chinese": "可能性；机会。",
        "english": "Något som går att göra eller chans att göra något.",
        "forms": "en möjlighet; möjligheten; möjligheter; möjligheterna",
        "example": "Det finns möjlighet att studera på distans.",
        "collocations": "ha möjlighet | 有机会；有可能 | Jag har möjlighet att studera.\nge möjlighet | 提供机会 | Skolan ger möjlighet till praktik.\nmöjlighet till praktik | 实习机会 | Det finns möjlighet till praktik.\nstor möjlighet | 很大机会；很大可能 | Det är en stor möjlighet.",
        "related_words": "chans | 机会；口语常用。\nval | 选择；常和 möjlighet 一起出现。\npotential | 潜力；较书面。\nmöjligen | 也许、可能；副词。",
        "favorite": false,
        "learned": false,
        "review_count": 0,
        "wrong_count": 0,
        "last_reviewed": null,
        "next_review_at": null,
        "created_at": null,
        "updated_at": null,
        "tags": [
          "SVA Grund 学习"
        ]
      },
      {
        "id": "word_fe9b18dda869f1d1",
        "swedish": "en skillnad",
        "pos": "noun",
        "pos_detail": "en",
        "chinese": "区别；差异。",
        "english": "När två saker inte är lika.",
        "forms": "en skillnad; skillnaden; skillnader; skillnaderna",
        "example": "Vad är skillnaden mellan orden?",
        "collocations": "stor skillnad | 很大差别 | Det är stor skillnad mellan orden.\ngöra skillnad | 起作用；有影响 | Din hjälp gör skillnad.\nskillnad mellan | ……之间的区别 | Vad är skillnaden mellan dem?\nse skillnad | 看出差别 | Jag ser ingen skillnad.",
        "related_words": "skillnader | 差异；区别（名词复数）\nlikhet | 相同；相似（名词）\njämföra | 比较（动词）\nolik | 不同的（形容词）\nära nog | 几乎；差不多（短语）",
        "favorite": false,
        "learned": false,
        "review_count": 0,
        "wrong_count": 0,
        "last_reviewed": null,
        "next_review_at": null,
        "created_at": null,
        "updated_at": null,
        "tags": [
          "SVA Grund 阅读"
        ]
      },
      {
        "id": "word_38ad0ad5afedbdf6",
        "swedish": "ett exempel",
        "pos": "noun",
        "pos_detail": "ett",
        "chinese": "例子。",
        "english": "Något som visar hur något kan vara.",
        "forms": "ett exempel; exemplet; exempel; exemplen",
        "example": "Ge ett exempel från texten.",
        "collocations": "till exempel | 例如 | Till exempel kan man säga så.\nge exempel | 举例 | Kan du ge exempel?\nett tydligt exempel | 一个清楚的例子 | Det är ett tydligt exempel.\nexempel på | ……的例子 | Det finns många exempel på det.",
        "related_words": "exempelvis | 例如（副词）\ntill exempel | 例如（短语）\nförebild | 榜样；范例（名词）\nmodell | 模型；典范（名词）\nvisa | 展示；说明（动词）",
        "favorite": false,
        "learned": false,
        "review_count": 0,
        "wrong_count": 0,
        "last_reviewed": null,
        "next_review_at": null,
        "created_at": null,
        "updated_at": null,
        "tags": [
          "SVA Grund 写作"
        ]
      },
      {
        "id": "word_dbb9ffab19c61c41",
        "swedish": "tydlig",
        "pos": "adjective",
        "pos_detail": "adj.",
        "chinese": "清楚的；明确的。",
        "english": "Lätt att förstå eller se.",
        "forms": "en: tydlig; ett: tydligt; plural: tydliga",
        "example": "Skriv en tydlig rubrik.",
        "collocations": "tydligt exempel | 清楚的例子 | Det är ett tydligt exempel.\ntydliga regler | 明确的规则 | Vi behöver tydliga regler.\nvara tydlig med | 明确说明；说清楚 | Var tydlig med ditt svar.\ntydligt språk | 清楚的语言 | Hon skriver med tydligt språk.",
        "related_words": "klar | 清楚的\notydlig | 不清楚的\nförklara | 解释",
        "favorite": false,
        "learned": false,
        "review_count": 0,
        "wrong_count": 0,
        "last_reviewed": null,
        "next_review_at": null,
        "created_at": null,
        "updated_at": null,
        "tags": [
          "SVA Grund 写作"
        ]
      },
      {
        "id": "word_752a8a55bde8327d",
        "swedish": "viktig",
        "pos": "adjective",
        "pos_detail": "adj.",
        "chinese": "重要的。",
        "english": "Important.",
        "forms": "en: viktig; ett: viktigt; plural: viktiga",
        "example": "Det är viktigt att komma i tid.",
        "collocations": "viktig information | 重要信息 | Det är viktig information.\nviktigt för hälsan | 对健康重要 | Sömn är viktigt för hälsan.\nen viktig fråga | 一个重要问题 | Det är en viktig fråga.\nviktig del | 重要部分 | Det är en viktig del av arbetet.",
        "related_words": "betydelsefull | 重要的\ncentral | 核心的\nstor | 大的",
        "favorite": false,
        "learned": false,
        "review_count": 0,
        "wrong_count": 0,
        "last_reviewed": null,
        "next_review_at": null,
        "created_at": null,
        "updated_at": null,
        "tags": [
          "SVA Grund 常用"
        ]
      },
      {
        "id": "word_110713a556010c9e",
        "swedish": "möjlig",
        "pos": "adjective",
        "pos_detail": "adj.",
        "chinese": "可能的；可行的。",
        "english": "Possible.",
        "forms": "en: möjlig; ett: möjligt; plural: möjliga",
        "example": "Är det möjligt att byta grupp?",
        "collocations": "så snart som möjligt | 尽快 | Svara så snart som möjligt.\nmöjliga lösningar | 可行的解决办法 | Vi diskuterar möjliga lösningar.\ninte möjligt | 不可能；不行 | Det är inte möjligt nu.\nvara möjligt | 是可能的 | Är det möjligt att byta tid?",
        "related_words": "omöjlig | 不可能的\nkanske | 也许\nmöjlighet | 可能性",
        "favorite": false,
        "learned": false,
        "review_count": 0,
        "wrong_count": 0,
        "last_reviewed": null,
        "next_review_at": null,
        "created_at": null,
        "updated_at": null,
        "tags": [
          "SVA Grund 常用"
        ]
      },
      {
        "id": "word_90cd884f010971ca",
        "swedish": "däremot",
        "pos": "adverb",
        "pos_detail": "adv.",
        "chinese": "然而；相反地。",
        "english": "Används för att visa en motsats.",
        "forms": "däremot",
        "example": "Texten är kort. Däremot är den svår.",
        "collocations": "däremot tycker jag | 然而我认为 | Det är billigt. Däremot tycker jag att det är litet.\ndäremot visar texten | 然而这篇文章显示 | Däremot visar texten något annat.\nmen däremot | 但是；然而 | Jag kan inte komma, men däremot senare.\ndäremot är det svårt | 不过这很难 | Det är enkelt att läsa, men däremot är det svårt att förstå.",
        "related_words": "men | 但是（连词）\nfast | 但是；不过（连词）\nå andra sidan | 另一方面（短语）\nannorlunda | 不同地；不一样（副词）\nmotsats | 相反（名词）",
        "favorite": false,
        "learned": false,
        "review_count": 0,
        "wrong_count": 0,
        "last_reviewed": null,
        "next_review_at": null,
        "created_at": null,
        "updated_at": null,
        "tags": [
          "SVA Grund 连接词"
        ]
      },
      {
        "id": "word_c32682ab3c95cc50",
        "swedish": "därför",
        "pos": "adverb",
        "pos_detail": "adv.",
        "chinese": "因此；所以。",
        "english": "Therefore.",
        "forms": "därför",
        "example": "Bussen var sen, därför kom jag för sent.",
        "collocations": "därför att | 因为；由于 | Jag stannar hemma därför att jag är sjuk.\njust därför | 正因为如此 | Jag är trött, just därför går jag hem.\ndärför behöver vi | 所以我们需要 | Därför behöver vi mer tid.\ndärför kom jag | 所以我来了/所以我迟到了 | Bussen var sen, därför kom jag sent.",
        "related_words": "orsak | 原因（名词）\norsaka | 引起；造成（动词）\nalltså | 因此；也就是说（副词）\nför att | 因为；为了（短语）\nså | 所以；因此（副词/连词）",
        "favorite": false,
        "learned": false,
        "review_count": 0,
        "wrong_count": 0,
        "last_reviewed": null,
        "next_review_at": null,
        "created_at": null,
        "updated_at": null,
        "tags": [
          "SVA Grund 连接词"
        ]
      },
      {
        "id": "word_234aee6681d0d6f2",
        "swedish": "samtidigt",
        "pos": "adverb",
        "pos_detail": "adv.",
        "chinese": "同时；与此同时。",
        "english": "På samma tid.",
        "forms": "samtidigt",
        "example": "Det är svårt men samtidigt intressant.",
        "collocations": "samtidigt som | 在……的同时 | Han lyssnade samtidigt som han skrev.\nsamtidigt med | 与……同时发生 | Vi åt middag samtidigt med gästerna.\npå samma gång | 同时；一并 | Det är svårt att göra allt på samma gång.",
        "related_words": "på samma gång | 同时（短语）\nunder tiden | 同时；在此期间（短语）\nlikaså | 同样；也（副词）\nparallellt | 平行地；同时（副词）\nmen | 但是（连词）",
        "favorite": false,
        "learned": false,
        "review_count": 0,
        "wrong_count": 0,
        "last_reviewed": null,
        "next_review_at": null,
        "created_at": null,
        "updated_at": null,
        "tags": [
          "SVA Grund 连接词"
        ]
      },
      {
        "id": "word_f81648229cf8bb25",
        "swedish": "ta reda på",
        "pos": "verb",
        "pos_detail": "固定短语",
        "chinese": "查明；弄清楚。",
        "english": "Att undersöka och få veta något.",
        "forms": "imperativ: ta reda på; infinitiv: ta reda på; presens: tar reda på; preteritum: tog reda på; supinum: tagit reda på",
        "example": "Jag ska ta reda på när kursen börjar.",
        "collocations": "ta reda på fakta | 查明事实 | Jag ska ta reda på fakta först.\nta reda på mer | 进一步弄清楚 | Vi behöver ta reda på mer om kursen.\nta reda på orsaken | 查明原因 | Läraren vill ta reda på orsaken.",
        "related_words": "undersöka | 调查；研究（动词）\nkontrollera | 核对；检查（动词）\nförsöka få veta | 试着弄清楚（短语）\nforska | 研究；探究（动词）\nfråga | 问；询问（动词）",
        "favorite": false,
        "learned": false,
        "review_count": 0,
        "wrong_count": 0,
        "last_reviewed": null,
        "next_review_at": null,
        "created_at": null,
        "updated_at": null,
        "tags": [
          "SVA Grund 学习"
        ]
      },
      {
        "id": "word_1cbd4ec821371429",
        "swedish": "hålla med",
        "pos": "verb",
        "pos_detail": "vi + prep.",
        "chinese": "同意；赞同。",
        "english": "Att tycka likadant som någon annan.",
        "forms": "imperativ: håll med; infinitiv: hålla med; presens: håller med; preteritum: höll med; supinum: hållit med",
        "example": "Jag håller inte med författaren.",
        "collocations": "hålla med om | 同意某事 | Jag håller med om förslaget.\nhålla med någon | 同意某人 | Alla höll med honom.\nhålla helt med | 完全同意 | Jag håller helt med dig.",
        "related_words": "instämma | 同意；赞同（动词）\nvara överens | 意见一致（短语）\ngilla | 喜欢；认可（动词）\nåsikt | 观点；看法（名词）\nmotsätta sig | 反对（动词）",
        "favorite": false,
        "learned": false,
        "review_count": 0,
        "wrong_count": 0,
        "last_reviewed": null,
        "next_review_at": null,
        "created_at": null,
        "updated_at": null,
        "tags": [
          "SVA Grund 讨论"
        ]
      }
    ]
  },
  {
    "level": "SVA gymnasienivå",
    "notebook": "SVA Gymnasium 常用词",
    "words": [
      {
        "id": "word_6ce6cbecd6efb7ab",
        "swedish": "analysera",
        "pos": "verb",
        "pos_detail": "vt",
        "chinese": "分析；深入讨论材料、观点或原因。",
        "english": "Att undersöka något noga och tänka djupare om det.",
        "forms": "imperativ: analysera; infinitiv: analysera; presens: analyserar; preteritum: analyserade; supinum: analyserat",
        "example": "I uppgiften ska du analysera novellens budskap.",
        "collocations": "analysera en text | 分析一篇文章 | Vi ska analysera en text i dag.\nanalysera orsaker | 分析原因 | Du måste analysera orsakerna.\nkritiskt analysera | 批判性分析 | Eleverna ska kritiskt analysera materialet.",
        "related_words": "undersöka | 调查\ntext | 文本\nsystem | 系统",
        "favorite": false,
        "learned": false,
        "review_count": 0,
        "wrong_count": 0,
        "last_reviewed": null,
        "next_review_at": null,
        "created_at": null,
        "updated_at": null,
        "tags": [
          "SVA Gym 写作"
        ]
      },
      {
        "id": "word_06eb324d52215f42",
        "swedish": "argumentera",
        "pos": "verb",
        "pos_detail": "vi",
        "chinese": "论证；提出理由支持观点。",
        "english": "Att ge skäl för sin åsikt.",
        "forms": "imperativ: argumentera; infinitiv: argumentera; presens: argumenterar; preteritum: argumenterade; supinum: argumenterat",
        "example": "Du behöver argumentera tydligare i din debattartikel.",
        "collocations": "argumentera för | 为……辩护；支持 | Hon argumenterar för sin idé.\nargumentera emot | 反对；反驳 | De argumenterar emot förslaget.\nargumentera sakligt | 理性地论证 | Du ska argumentera sakligt i texten.",
        "related_words": "argument | 论点；支持自己观点的理由。\ndebatt | 辩论；公开讨论。\nåsikt | 观点；argumentera 常围绕它。\nbevisa | 证明；有时用来支持论证。",
        "favorite": false,
        "learned": false,
        "review_count": 0,
        "wrong_count": 0,
        "last_reviewed": null,
        "next_review_at": null,
        "created_at": null,
        "updated_at": null,
        "tags": [
          "SVA Gym 写作"
        ]
      },
      {
        "id": "word_fdfb7908dbbbdee9",
        "swedish": "resonera",
        "pos": "verb",
        "pos_detail": "vi",
        "chinese": "推理；展开讨论；从多个角度说明。",
        "english": "Att tänka och prata igenom något på ett klokt sätt.",
        "forms": "imperativ: resonera; infinitiv: resonera; presens: resonerar; preteritum: resonerade; supinum: resonerat",
        "example": "Resonera kring hur språket förändras över tid.",
        "collocations": "resonera kring | 围绕……展开讨论 | Vi ska resonera kring frågan.\nresonera om | 谈论并推理 | Läraren bad oss resonera om temat.\nföra ett resonemang | 展开论述 | Du måste föra ett tydligt resonemang.",
        "related_words": "resonemang | 论证；推理（名词）\nargumentera | 论证；争辩（动词）\nfundera | 思考；琢磨（动词）\ndiskutera | 讨论（动词）\nförklara | 解释；说明（动词）",
        "favorite": false,
        "learned": false,
        "review_count": 0,
        "wrong_count": 0,
        "last_reviewed": null,
        "next_review_at": null,
        "created_at": null,
        "updated_at": null,
        "tags": [
          "SVA Gym 口语"
        ]
      },
      {
        "id": "word_02d0af32c0554ac6",
        "swedish": "ifrågasätta",
        "pos": "verb",
        "pos_detail": "vt",
        "chinese": "质疑；提出疑问。",
        "english": "Att undra om något stämmer eller är rätt.",
        "forms": "imperativ: ifrågasätt; infinitiv: ifrågasätta; presens: ifrågasätter; preteritum: ifrågasatte; supinum: ifrågasatt",
        "example": "Forskaren ifrågasätter den gamla förklaringen.",
        "collocations": "ifrågasätta normen | 质疑规范 | Ungdomar ifrågasätter normen.\nifrågasätta beslutet | 质疑决定 | Hon ifrågasatte beslutet.\nbli ifrågasatt | 被质疑 | Hans uppgift blev ifrågasatt.",
        "related_words": "tvivla | 怀疑；不太相信，verb\nifrågasättande | 质疑；提出疑问，substantiv\nkritisk | 批判的；爱质疑的，adjektiv\nifrågasatt | 被质疑的；受怀疑的，adjektiv/partisip",
        "favorite": false,
        "learned": false,
        "review_count": 0,
        "wrong_count": 0,
        "last_reviewed": null,
        "next_review_at": null,
        "created_at": null,
        "updated_at": null,
        "tags": [
          "SVA Gym 学术"
        ]
      },
      {
        "id": "word_83c80e627a190969",
        "swedish": "tolka",
        "pos": "verb",
        "pos_detail": "vt",
        "chinese": "解读；解释意义。",
        "english": "Att förklara vad något betyder.",
        "forms": "imperativ: tolka; infinitiv: tolka; presens: tolkar; preteritum: tolkade; supinum: tolkat",
        "example": "Hur tolkar du slutet i novellen?",
        "collocations": "tolka en text | 解读一篇文本 | Hur tolkar du texten?\ntolka symboler | 解读符号 | Eleverna ska tolka symbolerna.\ntolkas som | 被理解为；被解释为 | Det kan tolkas som kritik.",
        "related_words": "tolkning | 解释；翻译；解读，名词。\növersätta | 翻译，把一种语言换成另一种。\nförstå | 理解；看懂，常用于日常表达。\ntydning | 释义；解释，较书面。",
        "favorite": false,
        "learned": false,
        "review_count": 0,
        "wrong_count": 0,
        "last_reviewed": null,
        "next_review_at": null,
        "created_at": null,
        "updated_at": null,
        "tags": [
          "SVA Gym 文学"
        ]
      },
      {
        "id": "word_692f791d7a248c51",
        "swedish": "hänvisa",
        "pos": "verb",
        "pos_detail": "vi + prep.",
        "chinese": "引用；指向；参考。",
        "english": "Att peka på eller referera till något.",
        "forms": "imperativ: hänvisa; infinitiv: hänvisa; presens: hänvisar; preteritum: hänvisade; supinum: hänvisat",
        "example": "Hänvisa till källan i slutet av stycket.",
        "collocations": "hänvisa till en källa | 引用来源 | Du måste hänvisa till en källa.\nhänvisa läsaren | 引导读者去看 | Författaren hänvisar läsaren vidare.\nkällhänvisa korrekt | 正确标注出处 | Du ska källhänvisa korrekt.",
        "related_words": "referera till | 参考；提及，verb\ncitera | 引用，verb\npeka på | 指向；指出，verbfras\nkällhänvisa | 注明出处，verb",
        "favorite": false,
        "learned": false,
        "review_count": 0,
        "wrong_count": 0,
        "last_reviewed": null,
        "next_review_at": null,
        "created_at": null,
        "updated_at": null,
        "tags": [
          "SVA Gym 写作"
        ]
      },
      {
        "id": "word_8700127f270eb319",
        "swedish": "en källa",
        "pos": "noun",
        "pos_detail": "en",
        "chinese": "来源；资料来源；引用出处。",
        "english": "En plats där information kommer ifrån.",
        "forms": "en källa; källan; källor; källorna",
        "example": "Använd minst två trovärdiga källor.",
        "collocations": "en trovärdig källa | 可靠来源 | Det är en trovärdig källa.\nhänvisa till källa | 引用来源 | Glöm inte att hänvisa till källa.\nprimär källa | 一手来源 | Brevet är en primär källa.",
        "related_words": "ursprung | 起源；来源，substantiv\nkälla till information | 信息来源，fras\ntrovärdig källa | 可靠来源，fras\nprimärkälla | 一手来源，substantiv",
        "favorite": false,
        "learned": false,
        "review_count": 0,
        "wrong_count": 0,
        "last_reviewed": null,
        "next_review_at": null,
        "created_at": null,
        "updated_at": null,
        "tags": [
          "SVA Gym 学术"
        ]
      },
      {
        "id": "word_4806b3c76c580873",
        "swedish": "ett påstående",
        "pos": "noun",
        "pos_detail": "ett",
        "chinese": "陈述；主张；论点。",
        "english": "Något man säger att något är eller stämmer.",
        "forms": "ett påstående; påståendet; påståenden; påståendena",
        "example": "Stöd ditt påstående med ett exempel.",
        "collocations": "starkt påstående | 强有力的主张 | Det är ett starkt påstående.\nbelägg ett påstående | 证明一个论点 | Du måste belägga ditt påstående.\nett rimligt påstående | 合理的说法 | Det är ett rimligt påstående.",
        "related_words": "påstå | 断言；声称，verb\nuttalande | 陈述；说法，substantiv\nargument | 论据；论点，substantiv\ntes | 论点；主张，substantiv",
        "favorite": false,
        "learned": false,
        "review_count": 0,
        "wrong_count": 0,
        "last_reviewed": null,
        "next_review_at": null,
        "created_at": null,
        "updated_at": null,
        "tags": [
          "SVA Gym 写作"
        ]
      },
      {
        "id": "word_ac25302fd771e0da",
        "swedish": "ett perspektiv",
        "pos": "noun",
        "pos_detail": "ett",
        "chinese": "视角；角度。",
        "english": "Ett sätt att se på något.",
        "forms": "ett perspektiv; perspektivet; perspektiv; perspektiven",
        "example": "Försök se frågan ur ett annat perspektiv.",
        "collocations": "ur ett perspektiv | 从某个角度 | Man kan se det ur ett annat perspektiv.\nolika perspektiv | 不同视角 | Vi jämför olika perspektiv.\nhistoriskt perspektiv | 历史视角 | Texten ges i historiskt perspektiv.",
        "related_words": "synsätt | 看法；观点，substantiv\nvinkel | 角度，substantiv\nståndpunkt | 立场；观点，substantiv\nutsikt | 景色；视野，也可比喻视角，substantiv",
        "favorite": false,
        "learned": false,
        "review_count": 0,
        "wrong_count": 0,
        "last_reviewed": null,
        "next_review_at": null,
        "created_at": null,
        "updated_at": null,
        "tags": [
          "SVA Gym 分析"
        ]
      },
      {
        "id": "word_eff449cfb52fdee3",
        "swedish": "en konsekvens",
        "pos": "noun",
        "pos_detail": "en",
        "chinese": "后果；结果。",
        "english": "Något som händer som följd av något annat.",
        "forms": "en konsekvens; konsekvensen; konsekvenser; konsekvenserna",
        "example": "En konsekvens av stress kan vara sämre sömn.",
        "collocations": "få konsekvenser | 产生后果 | Det kan få konsekvenser.\nallvarliga konsekvenser | 严重后果 | Stress kan ge allvarliga konsekvenser.\nkonsekvens av | ……的后果 | Det är en konsekvens av beslutet.",
        "related_words": "följd | 后果；结果，substantiv\nresultat | 结果，substantiv\npåföljd | 惩罚；后果，substantiv\nkonsekvens av | ……的后果，fras",
        "favorite": false,
        "learned": false,
        "review_count": 0,
        "wrong_count": 0,
        "last_reviewed": null,
        "next_review_at": null,
        "created_at": null,
        "updated_at": null,
        "tags": [
          "SVA Gym 社会"
        ]
      },
      {
        "id": "word_f29e3e01993e810e",
        "swedish": "en förutsättning",
        "pos": "noun",
        "pos_detail": "en",
        "chinese": "前提；条件。",
        "english": "Något som måste finnas eller vara uppfyllt för att något annat ska kunna hända.",
        "forms": "en förutsättning; förutsättningen; förutsättningar; förutsättningarna",
        "example": "Språket är en viktig förutsättning för studier.",
        "collocations": "goda förutsättningar | 良好条件 | De har goda förutsättningar.\nskapa förutsättningar | 创造条件 | Skolan vill skapa förutsättningar för lärande.\nen förutsättning för | ……的前提 | Språket är en förutsättning för jobb.",
        "related_words": "villkor | 条件，substantiv\nkrav | 要求；必要条件，substantiv\ngrund | 基础；前提，substantiv\nnödvändig | 必要的，adjektiv",
        "favorite": false,
        "learned": false,
        "review_count": 0,
        "wrong_count": 0,
        "last_reviewed": null,
        "next_review_at": null,
        "created_at": null,
        "updated_at": null,
        "tags": [
          "SVA Gym 学术"
        ]
      },
      {
        "id": "word_6d1d7883c5dc8ddf",
        "swedish": "ett sammanhang",
        "pos": "noun",
        "pos_detail": "ett",
        "chinese": "语境；上下文；关联。",
        "english": "Det som visar hur något hänger ihop med det som finns runt omkring.",
        "forms": "ett sammanhang; sammanhanget; sammanhang; sammanhangen",
        "example": "Ordet får en annan betydelse i det här sammanhanget.",
        "collocations": "i ett sammanhang | 在某个语境中 | Ordet används i ett sammanhang.\nsocialt sammanhang | 社会环境；社交场合 | Det känns lättare i ett socialt sammanhang.\nsätta i sammanhang | 放入语境中 | Du måste sätta texten i sammanhang.",
        "related_words": "kontext | 语境；上下文，substantiv\nsamband | 联系；关联，substantiv\nomgivning | 周围环境，substantiv\nhelhet | 整体，substantiv",
        "favorite": false,
        "learned": false,
        "review_count": 0,
        "wrong_count": 0,
        "last_reviewed": null,
        "next_review_at": null,
        "created_at": null,
        "updated_at": null,
        "tags": [
          "SVA Gym 阅读"
        ]
      },
      {
        "id": "word_91a40b9083782400",
        "swedish": "relevant",
        "pos": "adjective",
        "pos_detail": "adj.",
        "chinese": "相关的；切题的。",
        "english": "Relevant.",
        "forms": "en: relevant; ett: relevant; plural: relevanta",
        "example": "Välj relevanta exempel från texten.",
        "collocations": "relevant information | 相关信息 | Jag saknar relevant information.\nrelevant för ämnet | 与主题相关 | Det är relevant för ämnet.\nmycket relevant | 非常相关 | Exemplet är mycket relevant.",
        "related_words": "viktig | 重要的，adjektiv\npassande | 合适的；切题的，adjektiv\nangelägen | 紧要的；相关的，adjektiv\nrelevans | 相关性，substantiv",
        "favorite": false,
        "learned": false,
        "review_count": 0,
        "wrong_count": 0,
        "last_reviewed": null,
        "next_review_at": null,
        "created_at": null,
        "updated_at": null,
        "tags": [
          "SVA Gym 写作"
        ]
      },
      {
        "id": "word_bfbe1d231476cf5a",
        "swedish": "trovärdig",
        "pos": "adjective",
        "pos_detail": "adj.",
        "chinese": "可信的；可靠的。",
        "english": "Som verkar sann och går att lita på.",
        "forms": "en: trovärdig; ett: trovärdigt; plural: trovärdiga",
        "example": "Är källan trovärdig?",
        "collocations": "trovärdig källa | 可信来源 | Det är en trovärdig källa.\ntrovärdigt argument | 可信的论点 | Hon gav ett trovärdigt argument.\nverka trovärdig | 显得可信 | Du måste verka trovärdig.",
        "related_words": "pålitlig | 可靠的，adjektiv\növertygande | 有说服力的，adjektiv\nsannolik | 可信的；可能的，adjektiv\ncredibel | 可信的，书面语/借词",
        "favorite": false,
        "learned": false,
        "review_count": 0,
        "wrong_count": 0,
        "last_reviewed": null,
        "next_review_at": null,
        "created_at": null,
        "updated_at": null,
        "tags": [
          "SVA Gym 学术"
        ]
      },
      {
        "id": "word_129346a054b88882",
        "swedish": "nyanserad",
        "pos": "adjective",
        "pos_detail": "adj.",
        "chinese": "有层次的；不片面的；细致平衡的。",
        "english": "Som visar flera sidor och inte är enkel eller ensidig.",
        "forms": "en: nyanserad; ett: nyanserat; plural: nyanserade",
        "example": "Texten innehåller ett nyanserat resonemang.",
        "collocations": "nyanserad bild | 全面的；有层次的看法 | Texten ger en nyanserad bild.\nnyanserat språk | 细致、委婉的语言 | Författaren använder ett nyanserat språk.\nnyanserade argument | 有层次的论据 | Han kom med nyanserade argument.",
        "related_words": "balanserad | 平衡的；不偏激的，adjektiv\nmångsidig | 多方面的，adjektiv\ndetaljerad | 细致的，adjektiv\nensidig | 单方面的；片面的，adjektiv",
        "favorite": false,
        "learned": false,
        "review_count": 0,
        "wrong_count": 0,
        "last_reviewed": null,
        "next_review_at": null,
        "created_at": null,
        "updated_at": null,
        "tags": [
          "SVA Gym 高级表达"
        ]
      },
      {
        "id": "word_7144fe667c738cb8",
        "swedish": "översiktlig",
        "pos": "adjective",
        "pos_detail": "adj.",
        "chinese": "概括性的；概要的。",
        "english": "Som ger en kort och allmän bild av något.",
        "forms": "en: översiktlig; ett: översiktligt; plural: översiktliga",
        "example": "Ge en översiktlig sammanfattning av artikeln.",
        "collocations": "översiktlig bild | 概览 | Här får du en översiktlig bild.\növersiktligt beskriva | 概述；简要描述 | Kan du översiktligt beskriva arbetet?\nen översiktlig analys | 概括性分析 | Vi gör en översiktlig analys.",
        "related_words": "kortfattad | 简短的；概括的，adjektiv\nallmän | 一般的；总体的，adjektiv\nsammanfattande | 总结性的，adjektiv\növersikt | 概览；总览，substantiv",
        "favorite": false,
        "learned": false,
        "review_count": 0,
        "wrong_count": 0,
        "last_reviewed": null,
        "next_review_at": null,
        "created_at": null,
        "updated_at": null,
        "tags": [
          "SVA Gym 学术"
        ]
      },
      {
        "id": "word_0ca58f8ff4f042d4",
        "swedish": "dessutom",
        "pos": "adverb",
        "pos_detail": "adv.",
        "chinese": "此外；而且。",
        "english": "Furthermore; moreover.",
        "forms": "dessutom",
        "example": "Texten är tydlig. Dessutom har den bra exempel.",
        "collocations": "dessutom visar | 而且显示 | Texten är tydlig och dessutom visar den resultat.\ndessutom menar | 此外还认为 | Författaren menar dessutom att...\ndessutom kan man | 此外还可以 | Dessutom kan man jämföra med andra fall.",
        "related_words": "också | 也；而且，adverb\näven | 也；甚至，adverb\nytterligare | 另外的；进一步的，adjektiv/adverb\nplus | 加上；而且，conj/adverb",
        "favorite": false,
        "learned": false,
        "review_count": 0,
        "wrong_count": 0,
        "last_reviewed": null,
        "next_review_at": null,
        "created_at": null,
        "updated_at": null,
        "tags": [
          "SVA Gym 连接词"
        ]
      },
      {
        "id": "word_8dcb06c2e6396a58",
        "swedish": "emellertid",
        "pos": "adverb",
        "pos_detail": "adv.",
        "chinese": "然而；不过，偏正式书面语。",
        "english": "However.",
        "forms": "emellertid",
        "example": "Resultatet är positivt. Emellertid finns det problem.",
        "collocations": "emellertid visar | 然而显示 | Resultatet visar emellertid något annat.\ndet finns emellertid | 然而存在 | Det finns emellertid ett problem.\nemellertid bör | 不过应该 | Man bör emellertid tänka på riskerna.",
        "related_words": "dock | 然而；不过，adverb\nändå | 仍然；不过，adverb\nmen | 但是，konjunktion\nfast | 不过；可是，口语/书面语",
        "favorite": false,
        "learned": false,
        "review_count": 0,
        "wrong_count": 0,
        "last_reviewed": null,
        "next_review_at": null,
        "created_at": null,
        "updated_at": null,
        "tags": [
          "SVA Gym 连接词"
        ]
      },
      {
        "id": "word_e8bbe4852ac21418",
        "swedish": "å ena sidan",
        "pos": "phrase",
        "pos_detail": "固定表达",
        "chinese": "一方面。",
        "english": "Används när man vill visa ett första perspektiv eller en sida av något.",
        "forms": "å ena sidan",
        "example": "Å ena sidan är tekniken praktisk, å andra sidan kan den skapa stress.",
        "collocations": "å ena sidan ... å andra sidan | 一方面……另一方面…… | Å ena sidan är det bra, å andra sidan är det dyrt.\nå ena sidan kan man säga | 一方面可以说 | Å ena sidan kan man säga att det sparar tid.\nå andra sidan | 另一方面 | Å andra sidan behöver vi mer information.\nse saken från två håll | 从两方面看问题 | Vi måste se saken från två håll.",
        "related_words": "å andra sidan | 另一方面，phrase\nför det första | 首先，phrase\nsamtidigt | 同时；不过，adverb\nbåde ... och | 既……又……，konjunktionfras",
        "favorite": false,
        "learned": false,
        "review_count": 0,
        "wrong_count": 0,
        "last_reviewed": null,
        "next_review_at": null,
        "created_at": null,
        "updated_at": null,
        "tags": [
          "SVA Gym 论证"
        ]
      },
      {
        "id": "word_6606eeaf769ebc06",
        "swedish": "dra slutsatsen",
        "pos": "verb",
        "pos_detail": "固定短语",
        "chinese": "得出结论。",
        "english": "Att komma fram till en slutsats efter att man tänkt eller läst något.",
        "forms": "imperativ: dra slutsatsen; infinitiv: dra slutsatsen; presens: drar slutsatsen; preteritum: drog slutsatsen; supinum: dragit slutsatsen",
        "example": "Man kan dra slutsatsen att språket påverkar identiteten.",
        "collocations": "dra slutsatsen att | 得出……的结论 | Man kan dra slutsatsen att det stämmer.\nrimlig slutsats | 合理的结论 | Det är en rimlig slutsats.\nkomma fram till en slutsats | 得出结论 | Vi kom fram till en slutsats.",
        "related_words": "slutsats | 结论，substantiv\nkomma fram till | 得出；达到，verbfras\nresonera | 推理；思考，verb\nkonkludera | 得出结论，书面语/verb",
        "favorite": false,
        "learned": false,
        "review_count": 0,
        "wrong_count": 0,
        "last_reviewed": null,
        "next_review_at": null,
        "created_at": null,
        "updated_at": null,
        "tags": [
          "SVA Gym 论证"
        ]
      }
    ]
  },
  {
    "level": "Vardag och samhälle",
    "notebook": "Vardag & samhälle",
    "words": [
      {
        "id": "word_eb241f62d9c70b31",
        "swedish": "hämta",
        "pos": "verb",
        "pos_detail": "vt",
        "chinese": "取；接；去拿。",
        "english": "Att gå och ta något eller någon och komma tillbaka med det.",
        "forms": "imperativ: hämta; infinitiv: hämta; presens: hämtar; preteritum: hämtade; supinum: hämtat",
        "example": "Jag hämtar barnen på förskolan klockan tre.",
        "collocations": "hämta barnen | 去接孩子 | Jag hämtar barnen efter jobbet.\nhämta paket | 取包裹 | Jag ska hämta paket på posten.\nhämta något från | 从……取来 | Kan du hämta vatten från köket?",
        "related_words": "lämna | 送、留下\nfå | 得到\nta | 拿",
        "favorite": false,
        "learned": false,
        "review_count": 0,
        "wrong_count": 0,
        "last_reviewed": null,
        "next_review_at": null,
        "created_at": null,
        "updated_at": null,
        "tags": [
          "Vardag"
        ]
      },
      {
        "id": "word_001edfb0ea7dd25d",
        "swedish": "lämna",
        "pos": "verb",
        "pos_detail": "vt",
        "chinese": "留下；交；送到；离开。",
        "english": "Att ge bort, lämna in eller åka därifrån.",
        "forms": "imperativ: lämna; infinitiv: lämna; presens: lämnar; preteritum: lämnade; supinum: lämnat",
        "example": "Hon lämnar in blanketten på kontoret.",
        "collocations": "lämna in | 交上；递交 | Lämna in uppgiften i dag.\nlämna barnen | 把孩子送去；送孩子 | Vi lämnar barnen på skolan.\nlämna tillbaka | 归还 | Jag ska lämna tillbaka boken.",
        "related_words": "ge | 给\nåka | 离开\nbyta | 换",
        "favorite": false,
        "learned": false,
        "review_count": 0,
        "wrong_count": 0,
        "last_reviewed": null,
        "next_review_at": null,
        "created_at": null,
        "updated_at": null,
        "tags": [
          "Vardag"
        ]
      },
      {
        "id": "word_5f62d88bffbe1a7f",
        "swedish": "träffa",
        "pos": "verb",
        "pos_detail": "vt",
        "chinese": "见面；遇见。",
        "english": "Att möta eller vara tillsammans med någon.",
        "forms": "imperativ: träffa; infinitiv: träffa; presens: träffar; preteritum: träffade; supinum: träffat",
        "example": "Jag ska träffa min handläggare i morgon.",
        "collocations": "träffa en vän | 见一位朋友 | Jag ska träffa en vän.\nträffa läkaren | 看医生；见医生 | Hon ska träffa läkaren i dag.\nträffa någon på | 在……见到某人 | Jag träffar honom på stationen.",
        "related_words": "möta | 遇见\nses | 见面\nvän | 朋友",
        "favorite": false,
        "learned": false,
        "review_count": 0,
        "wrong_count": 0,
        "last_reviewed": null,
        "next_review_at": null,
        "created_at": null,
        "updated_at": null,
        "tags": [
          "Vardag"
        ]
      },
      {
        "id": "word_8d0efdf7b4860efb",
        "swedish": "vänta",
        "pos": "verb",
        "pos_detail": "vi",
        "chinese": "等待。",
        "english": "Att vara kvar tills något händer eller någon kommer.",
        "forms": "imperativ: vänta; infinitiv: vänta; presens: väntar; preteritum: väntade; supinum: väntat",
        "example": "Vi väntar på bussen utanför stationen.",
        "collocations": "vänta på | 等待…… | Jag väntar på bussen.\nvänta lite | 等一会儿 | Kan du vänta lite?\nvänta sig | 期待；预料 | Vad väntar du dig?",
        "related_words": "tid | 时间\nsen | 晚的\nhållplats | 车站",
        "favorite": false,
        "learned": false,
        "review_count": 0,
        "wrong_count": 0,
        "last_reviewed": null,
        "next_review_at": null,
        "created_at": null,
        "updated_at": null,
        "tags": [
          "Vardag"
        ]
      },
      {
        "id": "word_fe8e4fa5591ee7de",
        "swedish": "skicka",
        "pos": "verb",
        "pos_detail": "vt",
        "chinese": "发送；寄。",
        "english": "Att sända något till någon.",
        "forms": "imperativ: skicka; infinitiv: skicka; presens: skickar; preteritum: skickade; supinum: skickat",
        "example": "Skicka ett mejl till läraren.",
        "collocations": "skicka mejl | 发邮件 | Jag ska skicka mejl till läraren.\nskicka in | 提交；寄出 | Skicka in ansökan i dag.\nskicka iväg | 发送出去 | Hon skickade iväg ett sms.",
        "related_words": "meddelande | 消息\nbrev | 信\nmejla | 发邮件",
        "favorite": false,
        "learned": false,
        "review_count": 0,
        "wrong_count": 0,
        "last_reviewed": null,
        "next_review_at": null,
        "created_at": null,
        "updated_at": null,
        "tags": [
          "Samhälle"
        ]
      },
      {
        "id": "word_542fdc9e5a239cf9",
        "swedish": "anmäla",
        "pos": "verb",
        "pos_detail": "vt",
        "chinese": "报名；申报；报告。",
        "english": "Att säga till, registrera sig eller rapportera något.",
        "forms": "imperativ: anmäl; infinitiv: anmäla; presens: anmäler; preteritum: anmälde; supinum: anmält",
        "example": "Du måste anmäla frånvaro i appen.",
        "collocations": "anmäla sig | 报名；登记 | Jag vill anmäla mig till kursen.\nanmäla frånvaro | 请假报缺席 | Du måste anmäla frånvaro i dag.\nanmäla ett fel | 报告一个错误 | Jag vill anmäla ett fel.",
        "related_words": "registrera | 登记\nrapportera | 报告\nsjukdom | 疾病",
        "favorite": false,
        "learned": false,
        "review_count": 0,
        "wrong_count": 0,
        "last_reviewed": null,
        "next_review_at": null,
        "created_at": null,
        "updated_at": null,
        "tags": [
          "Samhälle"
        ]
      },
      {
        "id": "word_7c920ddcc34d2462",
        "swedish": "godkänna",
        "pos": "verb",
        "pos_detail": "vt",
        "chinese": "批准；认可；通过。",
        "english": "Att säga ja till något eller att något får vara med.",
        "forms": "imperativ: godkänn; infinitiv: godkänna; presens: godkänner; preteritum: godkände; supinum: godkänt",
        "example": "Läraren godkände min uppgift.",
        "collocations": "bli godkänd | 被批准；通过 | Hon blev godkänd på provet.\ngodkänna villkor | 同意条款 | Du måste godkänna villkoren.\ngodkänna en uppgift | 批准一项作业 | Läraren godkände uppgiften.",
        "related_words": "acceptera | 接受\nbekräfta | 确认\nnek﻿a | 拒绝",
        "favorite": false,
        "learned": false,
        "review_count": 0,
        "wrong_count": 0,
        "last_reviewed": null,
        "next_review_at": null,
        "created_at": null,
        "updated_at": null,
        "tags": [
          "Studier"
        ]
      },
      {
        "id": "word_ac5112c0551b2398",
        "swedish": "en vårdcentral",
        "pos": "noun",
        "pos_detail": "en",
        "chinese": "社区医疗中心；瑞典初级医疗机构。",
        "english": "En plats där man får vård när man är sjuk eller behöver hjälp.",
        "forms": "en vårdcentral; vårdcentralen; vårdcentraler; vårdcentralerna",
        "example": "Ring vårdcentralen om du behöver råd.",
        "collocations": "kontakta vårdcentralen | 联系社区医疗中心 | Kontakta vårdcentralen vid feber.\nlista sig på vårdcentral | 在社区医疗中心登记 | Jag vill lista mig på en vårdcentral.\nbesöka vårdcentralen | 去社区医疗中心就诊 | Hon ska besöka vårdcentralen.",
        "related_words": "sjukhus | 医院，substantiv\nläkarmottagning | 医生门诊，substantiv\nprimärvård | 初级医疗，substantiv\n1177 | 医疗咨询电话/网站，专有名词",
        "favorite": false,
        "learned": false,
        "review_count": 0,
        "wrong_count": 0,
        "last_reviewed": null,
        "next_review_at": null,
        "created_at": null,
        "updated_at": null,
        "tags": [
          "Vård"
        ]
      },
      {
        "id": "word_d599efb508e8fbcc",
        "swedish": "ett recept",
        "pos": "noun",
        "pos_detail": "ett",
        "chinese": "处方；食谱。",
        "english": "En skriftlig lapp från läkare med medicin, eller en beskrivning av hur man lagar mat.",
        "forms": "ett recept; receptet; recept; recepten",
        "example": "Läkaren skrev ut ett recept.",
        "collocations": "hämta ut recept | 取处方药 | Jag ska hämta ut receptet.\nelektroniskt recept | 电子处方 | Receptet finns elektroniskt.\nförnya recept | 续方 | Jag behöver förnya mitt recept.",
        "related_words": "läkemedel | 药物，substantiv\nordination | 医嘱；处方，substantiv\nskriva ut recept | 开处方，verbfras\nförnya recept | 续处方，verbfras",
        "favorite": false,
        "learned": false,
        "review_count": 0,
        "wrong_count": 0,
        "last_reviewed": null,
        "next_review_at": null,
        "created_at": null,
        "updated_at": null,
        "tags": [
          "Vård"
        ]
      },
      {
        "id": "word_4452a722e39817f2",
        "swedish": "ett apotek",
        "pos": "noun",
        "pos_detail": "ett",
        "chinese": "药店。",
        "english": "En butik där man köper medicin.",
        "forms": "ett apotek; apoteket; apotek; apoteken",
        "example": "Apoteket stänger klockan sex.",
        "collocations": "gå till apoteket | 去药店 | Jag går till apoteket efter jobbet.\nköpa medicin | 买药 | Du kan köpa medicin på apoteket.\nhämta ut på apoteket | 在药店领取 | Jag hämtar ut det på apoteket.",
        "related_words": "medicin | 药；药品，substantiv\nläkemedel | 药物，substantiv\napoteksvara | 药店商品，substantiv\nreceptbelagd | 处方药的，adjektiv",
        "favorite": false,
        "learned": false,
        "review_count": 0,
        "wrong_count": 0,
        "last_reviewed": null,
        "next_review_at": null,
        "created_at": null,
        "updated_at": null,
        "tags": [
          "Vård"
        ]
      },
      {
        "id": "word_fc6d3fb3b2d2179d",
        "swedish": "en förskola",
        "pos": "noun",
        "pos_detail": "en",
        "chinese": "幼儿园；学前班前的托育机构。",
        "english": "En plats för små barn före skolan.",
        "forms": "en förskola; förskolan; förskolor; förskolorna",
        "example": "Min dotter går på förskola nära vårt hem.",
        "collocations": "gå på förskola | 上幼儿园 | Barnet går på förskola.\nhämta på förskolan | 去幼儿园接孩子 | Jag hämtar på förskolan klockan fyra.\nstarta förskola | 开始上幼儿园 | Min son ska starta förskola.",
        "related_words": "dagis | 托儿所；口语，substantiv\nbarnomsorg | 幼儿照护，substantiv\nförskollärare | 幼儿园老师，substantiv\nförskolebarn | 幼儿园儿童，substantiv",
        "favorite": false,
        "learned": false,
        "review_count": 0,
        "wrong_count": 0,
        "last_reviewed": null,
        "next_review_at": null,
        "created_at": null,
        "updated_at": null,
        "tags": [
          "Skola"
        ]
      },
      {
        "id": "word_a77818f99562a4c1",
        "swedish": "ett betyg",
        "pos": "noun",
        "pos_detail": "ett",
        "chinese": "成绩；评分。",
        "english": "Ett omdöme eller en siffra som visar hur det har gått i skolan.",
        "forms": "ett betyg; betyget; betyg; betygen",
        "example": "Jag vill höja mitt betyg i svenska.",
        "collocations": "få betyg | 得到成绩 | Eleverna får betyg i juni.\nhöja betyget | 提高成绩 | Hon vill höja betyget.\nsänka betyget | 降低成绩 | Ett missat prov kan sänka betyget.",
        "related_words": "bedömning | 评价、评定（名词）\nprov | 考试、测验（名词）\ngodkänd | 及格的、被批准的（形容词）\nunderkänd | 不及格的（形容词）",
        "favorite": false,
        "learned": false,
        "review_count": 0,
        "wrong_count": 0,
        "last_reviewed": null,
        "next_review_at": null,
        "created_at": null,
        "updated_at": null,
        "tags": [
          "Studier"
        ]
      },
      {
        "id": "word_9f74f91f5cf71556",
        "swedish": "en arbetsgivare",
        "pos": "noun",
        "pos_detail": "en",
        "chinese": "雇主。",
        "english": "En person eller ett företag som anställer människor att arbeta.",
        "forms": "en arbetsgivare; arbetsgivaren; arbetsgivare; arbetsgivarna",
        "example": "Arbetsgivaren ringde mig efter intervjun.",
        "collocations": "kontakta arbetsgivaren | 联系雇主；和雇主联系 | Kontakta arbetsgivaren om schemat.\nbyta arbetsgivare | 更换雇主；换工作单位 | Hon vill byta arbetsgivare.\nnuvarande arbetsgivare | 现任雇主 | Min nuvarande arbetsgivare är snäll.\ntidigare arbetsgivare | 以前的雇主 | Min tidigare arbetsgivare skrev ett intyg.",
        "related_words": "arbetsplats | 工作场所（名词）\narbetstagare | 雇员、受雇者（名词）\nchef | 老板、主管（名词）\nanställa | 雇用（动词）",
        "favorite": false,
        "learned": false,
        "review_count": 0,
        "wrong_count": 0,
        "last_reviewed": null,
        "next_review_at": null,
        "created_at": null,
        "updated_at": null,
        "tags": [
          "Jobb"
        ]
      },
      {
        "id": "word_89ccea3436aba294",
        "swedish": "en anställning",
        "pos": "noun",
        "pos_detail": "en",
        "chinese": "雇佣；职位。",
        "english": "Ett arbete som man har hos en arbetsgivare.",
        "forms": "en anställning; anställningen; anställningar; anställningarna",
        "example": "Hon fick en fast anställning.",
        "collocations": "fast anställning | 正式工作；长期雇佣 | Han söker fast anställning.\ntidsbegränsad anställning | 有期限的工作；临时雇佣 | Det är en tidsbegränsad anställning.\nbörja en anställning | 开始一份工作 | Hon börjar sin anställning i april.\nha en anställning | 拥有一份工作 | Han har en anställning på sjukhuset.",
        "related_words": "anställa | 雇用（动词）\narbetsgivare | 雇主（名词）\njobb | 工作（名词）\nheltid | 全职（名词/副词）",
        "favorite": false,
        "learned": false,
        "review_count": 0,
        "wrong_count": 0,
        "last_reviewed": null,
        "next_review_at": null,
        "created_at": null,
        "updated_at": null,
        "tags": [
          "Jobb"
        ]
      },
      {
        "id": "word_ed73a8b7bf103dfd",
        "swedish": "ett schema",
        "pos": "noun",
        "pos_detail": "ett",
        "chinese": "时间表；排班表；课程表。",
        "english": "En plan som visar tider, lektioner eller arbetspass.",
        "forms": "ett schema; schemat; scheman; schemana",
        "example": "Mitt schema ändrades den här veckan.",
        "collocations": "ändra schema | 更改排班/时间表 | Chefen ändrade mitt schema.\nfölja schemat | 按照时间表进行 | Vi följer schemat varje dag.\nha schema | 有排班表/课程表 | Jag har schema hela veckan.\njobba enligt schemat | 按照排班工作 | Vi jobbar enligt schemat.",
        "related_words": "tidtabell | 时刻表（名词）\nplanering | 计划、安排（名词）\narbetstid | 工作时间（名词）\nlektion | 课、课程（名词）",
        "favorite": false,
        "learned": false,
        "review_count": 0,
        "wrong_count": 0,
        "last_reviewed": null,
        "next_review_at": null,
        "created_at": null,
        "updated_at": null,
        "tags": [
          "Jobb"
        ]
      },
      {
        "id": "word_58cb8bd72758b639",
        "swedish": "en myndighet",
        "pos": "noun",
        "pos_detail": "en",
        "chinese": "政府机构；行政机关。",
        "english": "En del av staten eller kommunen som sköter regler och beslut.",
        "forms": "en myndighet; myndigheten; myndigheter; myndigheterna",
        "example": "Du kan kontakta myndigheten via deras webbplats.",
        "collocations": "svensk myndighet | 瑞典官方机构 | Försäkringskassan är en svensk myndighet.\nkontakta en myndighet | 联系一个政府机构 | Jag behöver kontakta en myndighet.\nansöka hos myndigheten | 向机构申请 | Du kan ansöka hos myndigheten.\nhämta information från en myndighet | 从机构获取信息 | Jag fick information från myndigheten.",
        "related_words": "verk | 公署、局；如 Skatteverket、Migrationsverket。\nkontor | 办公室；常指办事地点。\nförvaltning | 行政管理；较正式。\nregering | 政府；最高政治执行机构。",
        "favorite": false,
        "learned": false,
        "review_count": 0,
        "wrong_count": 0,
        "last_reviewed": null,
        "next_review_at": null,
        "created_at": null,
        "updated_at": null,
        "tags": [
          "Samhälle"
        ]
      },
      {
        "id": "word_e62a6e23045b4a65",
        "swedish": "ett intyg",
        "pos": "noun",
        "pos_detail": "ett",
        "chinese": "证明；证明文件。",
        "english": "Ett papper som visar att något är sant eller riktigt.",
        "forms": "ett intyg; intyget; intyg; intygen",
        "example": "Jag behöver ett intyg från läkaren.",
        "collocations": "läkarintyg | 医生证明 | Jag behöver ett läkarintyg.\nskicka intyg | 发送证明文件 | Skicka intyget till skolan.\nvisa ett intyg | 出示证明 | Du måste visa ett intyg.\nbe om ett intyg | 索要一份证明 | Jag ska be om ett intyg.",
        "related_words": "bevis | 证明、证据（名词）\nläkarintyg | 医生证明（名词）\nblankett | 表格（名词）\nintyga | 证明、证实（动词）",
        "favorite": false,
        "learned": false,
        "review_count": 0,
        "wrong_count": 0,
        "last_reviewed": null,
        "next_review_at": null,
        "created_at": null,
        "updated_at": null,
        "tags": [
          "Samhälle"
        ]
      },
      {
        "id": "word_014e1c573721f48e",
        "swedish": "en avgift",
        "pos": "noun",
        "pos_detail": "en",
        "chinese": "费用；收费。",
        "english": "Pengar man måste betala för något.",
        "forms": "en avgift; avgiften; avgifter; avgifterna",
        "example": "Det finns ingen avgift för kursen.",
        "collocations": "betala avgift | 支付费用 | Du måste betala avgiften i tid.\nhög avgift | 高额费用 | Avgiften är ganska hög.\nlåg avgift | 低费用；便宜的收费 | De har en låg avgift.\nextra avgift | 额外费用 | Det tillkommer en extra avgift.",
        "related_words": "kostnad | 费用、成本（名词）\nbetalning | 付款（名词）\nräkning | 账单（名词）\nbetala | 支付（动词）",
        "favorite": false,
        "learned": false,
        "review_count": 0,
        "wrong_count": 0,
        "last_reviewed": null,
        "next_review_at": null,
        "created_at": null,
        "updated_at": null,
        "tags": [
          "Ekonomi"
        ]
      },
      {
        "id": "word_e40a27953ab9b97b",
        "swedish": "en inkomst",
        "pos": "noun",
        "pos_detail": "en",
        "chinese": "收入。",
        "english": "Income.",
        "forms": "en inkomst; inkomsten; inkomster; inkomsterna",
        "example": "Skriv din inkomst på blanketten.",
        "collocations": "låg inkomst | 低收入 | Familjen har låg inkomst.\nfast inkomst | 固定收入 | Banken frågar om fast inkomst.\nuppge inkomst | 填写收入 | Skriv din inkomst här.\nha inkomst | 有收入 | Hon har ingen inkomst just nu.",
        "related_words": "lön | 工资（名词）\npengar | 钱（名词）\nskatt | 税（名词）\nutgift | 支出、开销（名词）",
        "favorite": false,
        "learned": false,
        "review_count": 0,
        "wrong_count": 0,
        "last_reviewed": null,
        "next_review_at": null,
        "created_at": null,
        "updated_at": null,
        "tags": [
          "Ekonomi"
        ]
      },
      {
        "id": "word_b87db20f7cf2a22d",
        "swedish": "en skuld",
        "pos": "noun",
        "pos_detail": "en",
        "chinese": "债务；欠款。",
        "english": "Pengar som man är skyldig någon.",
        "forms": "en skuld; skulden; skulder; skulderna",
        "example": "Han vill betala av sina skulder.",
        "collocations": "ha skulder | 有债务 | Hon har inga skulder.\nbetala av skuld | 偿还债务 | Jag försöker betala av en skuld.\nstor skuld | 大笔债务 | Han har en stor skuld.\nkomma i skuld | 负债；欠债 | Det är lätt att komma i skuld.",
        "related_words": "låna | 借入、贷款（动词）\nlån | 贷款、借款（名词）\nbetala tillbaka | 还钱、偿还（动词短语）\nränta | 利息（名词）",
        "favorite": false,
        "learned": false,
        "review_count": 0,
        "wrong_count": 0,
        "last_reviewed": null,
        "next_review_at": null,
        "created_at": null,
        "updated_at": null,
        "tags": [
          "Ekonomi"
        ]
      },
      {
        "id": "word_d88f9a4aca8f8c46",
        "swedish": "trygg",
        "pos": "adjective",
        "pos_detail": "adj.",
        "chinese": "安全的；安心的；有保障的。",
        "english": "Som känns säker och lugn.",
        "forms": "en: trygg; ett: tryggt; plural: trygga",
        "example": "Jag känner mig trygg i området.",
        "collocations": "känna sig trygg | 感到安心/有安全感 | Barnen känner sig trygga i skolan.\ntrygg miljö | 安全的环境 | Skolan ska vara en trygg miljö.\nvara trygg med | 对……有把握 | Jag är trygg med svenska nu.\nkänna sig trygg i | 在……中感到安心 | Hon känner sig trygg i gruppen.",
        "related_words": "säker | 安全的\nanställningstrygghet | 就业保障\nrädd | 害怕的",
        "favorite": false,
        "learned": false,
        "review_count": 0,
        "wrong_count": 0,
        "last_reviewed": null,
        "next_review_at": null,
        "created_at": null,
        "updated_at": null,
        "tags": [
          "Vardag"
        ]
      },
      {
        "id": "word_f497a9bcd7518c5f",
        "swedish": "nöjd",
        "pos": "adjective",
        "pos_detail": "adj.",
        "chinese": "满意的。",
        "english": "Glad och belåten med något.",
        "forms": "en: nöjd; ett: nöjt; plural: nöjda",
        "example": "Jag är nöjd med kursen.",
        "collocations": "vara nöjd med | 对……满意 | Är du nöjd med resultatet?\nnöjd kund | 满意的顾客 | En nöjd kund kommer tillbaka.\nvara nöjd över | 对……感到满意/高兴 | Jag är nöjd över mitt jobb.\ninte nöjd | 不满意 | Han är inte nöjd med svaren.",
        "related_words": "missnöjd | 不满意的\nglad | 高兴的\nlycklig | 幸福的",
        "favorite": false,
        "learned": false,
        "review_count": 0,
        "wrong_count": 0,
        "last_reviewed": null,
        "next_review_at": null,
        "created_at": null,
        "updated_at": null,
        "tags": [
          "Vardag"
        ]
      },
      {
        "id": "word_c5c4636e4598cd89",
        "swedish": "trött",
        "pos": "adjective",
        "pos_detail": "adj.",
        "chinese": "累的；疲倦的。",
        "english": "Tired.",
        "forms": "en: trött; ett: trött; plural: trötta",
        "example": "Jag är trött efter jobbet.",
        "collocations": "vara trött på | 厌倦；受够了 | Jag är trött på att vänta.\nkänna sig trött | 感到疲倦 | Hon känner sig trött idag.\nvara jätte trött | 非常累 | Jag var jätte trött efter jobbet.\nblir trött av | 因……而累 | Jag blir trött av att läsa sent.",
        "related_words": "pigg | 精神好的\nsömnig | 困的\nvila | 休息",
        "favorite": false,
        "learned": false,
        "review_count": 0,
        "wrong_count": 0,
        "last_reviewed": null,
        "next_review_at": null,
        "created_at": null,
        "updated_at": null,
        "tags": [
          "Vardag"
        ]
      },
      {
        "id": "word_73ed8c1ebcd4efef",
        "swedish": "snart",
        "pos": "adverb",
        "pos_detail": "adv.",
        "chinese": "很快；不久。",
        "english": "Soon.",
        "forms": "snart",
        "example": "Bussen kommer snart.",
        "collocations": "så snart som möjligt | 尽快 | Svara så snart som möjligt.\nkommer snart | 马上就来 | Bussen kommer snart.\nvara snart klar | 很快就完成 | Jag är snart klar.\ninte så snart | 没那么快；暂时不会 | Det händer inte så snart.",
        "related_words": "strax | 马上、很快（副词）\nsenare | 稍后、以后（副词）\nnu | 现在（副词）\nom en stund | 过一会儿（短语）",
        "favorite": false,
        "learned": false,
        "review_count": 0,
        "wrong_count": 0,
        "last_reviewed": null,
        "next_review_at": null,
        "created_at": null,
        "updated_at": null,
        "tags": [
          "Tid"
        ]
      },
      {
        "id": "word_617f53b7b6b518c5",
        "swedish": "nästan",
        "pos": "adverb",
        "pos_detail": "adv.",
        "chinese": "几乎；差不多。",
        "english": "Almost.",
        "forms": "nästan",
        "example": "Jag är nästan färdig med uppgiften.",
        "collocations": "nästan alltid | 几乎总是 | Han kommer nästan alltid i tid.\nnästan klar | 几乎完成了 | Vi är nästan klara.\nnästan färdig | 差不多做好了 | Maten är nästan färdig.\nnästan ingen | 几乎没有 | Det är nästan ingen hemma.",
        "related_words": "ungefär | 大约、差不多（副词）\nknappt | 几乎不、勉强（副词）\nhelt | 完全（副词）\nnära | 接近、靠近（副词/形容词）",
        "favorite": false,
        "learned": false,
        "review_count": 0,
        "wrong_count": 0,
        "last_reviewed": null,
        "next_review_at": null,
        "created_at": null,
        "updated_at": null,
        "tags": [
          "Tid"
        ]
      },
      {
        "id": "word_979112f6e4db93ea",
        "swedish": "trots att",
        "pos": "phrase",
        "pos_detail": "bisatsinledare",
        "chinese": "尽管；虽然。",
        "english": "Används när något händer ändå, fast det finns ett hinder.",
        "forms": "trots att",
        "example": "Hon gick till jobbet trots att hon var trött.",
        "collocations": "trots att det regnar | 尽管下雨 | Vi går ut trots att det regnar.\ntrots att jag försökte | 尽管我试了 | Det gick inte trots att jag försökte.\ntrots att hon var trött | 尽管她很累 | Hon gick till jobbet trots att hon var trött.\ntrots att det var sent | 尽管已经很晚 | Vi fortsatte trots att det var sent.",
        "related_words": "även om | 即使、虽然（连词短语）\nfastän | 尽管、虽然（连词）\nmen | 但是（连词）\ntrots | 尽管（介词）",
        "favorite": false,
        "learned": false,
        "review_count": 0,
        "wrong_count": 0,
        "last_reviewed": null,
        "next_review_at": null,
        "created_at": null,
        "updated_at": null,
        "tags": [
          "Samband"
        ]
      },
      {
        "id": "word_2aff7a5a285b8423",
        "swedish": "på grund av",
        "pos": "phrase",
        "pos_detail": "prepositionsfras",
        "chinese": "由于；因为。",
        "english": "Används för att förklara varför något händer.",
        "forms": "på grund av",
        "example": "Tåget är sent på grund av snön.",
        "collocations": "på grund av vädret | 由于天气原因 | Matchen ställdes in på grund av vädret.\npå grund av sjukdom | 因病；由于生病 | Hon är hemma på grund av sjukdom.\npå grund av trafik | 由于交通原因 | Tåget är sent på grund av trafik.\npå grund av problem | 因为问题；由于故障 | Bussen stannar på grund av problem.",
        "related_words": "därför att | 因为（连词短语）\neftersom | 因为、由于（连词）\norsak | 原因（名词）\nbero på | 取决于、由于（动词短语）",
        "favorite": false,
        "learned": false,
        "review_count": 0,
        "wrong_count": 0,
        "last_reviewed": null,
        "next_review_at": null,
        "created_at": null,
        "updated_at": null,
        "tags": [
          "Samband"
        ]
      },
      {
        "id": "word_e946a85645a88b52",
        "swedish": "ta hand om",
        "pos": "verb",
        "pos_detail": "partikelverb",
        "chinese": "照顾；处理。",
        "english": "Att sköta, hjälpa eller se till att något blir gjort.",
        "forms": "imperativ: ta hand om; infinitiv: ta hand om; presens: tar hand om; preteritum: tog hand om; supinum: tagit hand om",
        "example": "Kan du ta hand om disken?",
        "collocations": "ta hand om barn | 照顾孩子 | Hon tar hand om barnen.\nta hand om ett problem | 处理一个问题 | Vi måste ta hand om problemet.\nta hand om disken | 洗碗；处理碗碟 | Kan du ta hand om disken?\nta hand om sig själv | 照顾自己 | Du måste ta hand om dig själv.",
        "related_words": "sköta | 照顾、处理（动词）\npassa | 照看、适合（动词）\nhjälpa | 帮助（动词）\nansvara för | 负责（动词短语）",
        "favorite": false,
        "learned": false,
        "review_count": 0,
        "wrong_count": 0,
        "last_reviewed": null,
        "next_review_at": null,
        "created_at": null,
        "updated_at": null,
        "tags": [
          "Vardag"
        ]
      },
      {
        "id": "word_9dc9b9a1e42f4f08",
        "swedish": "komma överens",
        "pos": "verb",
        "pos_detail": "frasverb",
        "chinese": "达成一致；相处融洽。",
        "english": "Att vara enig eller att fungera bra tillsammans.",
        "forms": "imperativ: kom överens; infinitiv: komma överens; presens: kommer överens; preteritum: kom överens; supinum: kommit överens",
        "example": "Vi kom överens om en ny tid.",
        "collocations": "komma överens om | 就……达成一致 | Vi kom överens om priset.\nkomma bra överens | 相处得很好 | De kommer bra överens.\nkomma överens med | 与……相处融洽 | Jag kommer överens med mina kollegor.\ninte komma överens | 合不来；没法达成一致 | Vi kom inte överens.",
        "related_words": "enas | 达成一致（动词）\nhålla med | 同意（动词短语）\nsamförstånd | 共识、相互理解（名词）\nbråka | 吵架、争执（动词）",
        "favorite": false,
        "learned": false,
        "review_count": 0,
        "wrong_count": 0,
        "last_reviewed": null,
        "next_review_at": null,
        "created_at": null,
        "updated_at": null,
        "tags": [
          "Samtal"
        ]
      }
    ]
  }
];
