-- Läsning multi-native-language support (Reviews/阅读模块多母语支持-架构方案-
-- 2026-09-01.md, decisions 1-3, approved by Rachel 2026-09-01). Mirrors the
-- word-corpus split already done for learning_object_translations: one
-- text_analysis row per (text_resource, native_language) instead of one row
-- per text_resource. "What to select" (selected_vocabulary/
-- selected_expressions/key_sentences/language_patterns' word_id/
-- expression_id/swedish/expression_text/sentence/pattern/sort_order/
-- occurrences fields) is reused across languages by copying it into a new
-- language's row (server-reading.mjs's explainExistingSelectionInLanguage);
-- only the embedded explanation text (still named *_zh for now — legacy
-- name, holds whatever language the row is for) gets freshly generated per
-- language.
--
-- status replaces relying on text_resources.analysis_status for
-- deep-readiness: that column is per-resource, but deep-readiness is now
-- per-(resource, language) since one resource can have a 'ready' zh row and
-- a 'summary_ready' en row at the same time. text_resources.analysis_status
-- keeps being written (whichever language most recently progressed) purely
-- as a rough legacy signal — nothing load-bearing reads it anymore.
alter table public.text_analysis
  add column if not exists native_language text not null default 'zh';

alter table public.text_analysis
  add column if not exists status text not null default 'summary_ready';

alter table public.text_analysis
  drop constraint if exists text_analysis_status_check;
alter table public.text_analysis
  add constraint text_analysis_status_check
    check (status in ('summary_ready', 'ready'));

-- Backfill existing rows (all zh, from before this migration): 'ready' if
-- the deep layer already populated vocabulary, else still 'summary_ready'.
update public.text_analysis
  set status = case when jsonb_array_length(selected_vocabulary) > 0 then 'ready' else 'summary_ready' end
  where native_language = 'zh';

-- Replace the old (text_resource_id, analysis_version) uniqueness with
-- (text_resource_id, analysis_version, native_language) — found by name via
-- pg_constraint rather than hardcoding it, since it was auto-generated by
-- Postgres from the original inline `unique (...)` at table-creation time.
do $$
declare
  c record;
begin
  for c in
    select conname from pg_constraint
    where conrelid = 'public.text_analysis'::regclass and contype = 'u'
  loop
    execute format('alter table public.text_analysis drop constraint %I', c.conname);
  end loop;
end $$;

alter table public.text_analysis
  add constraint text_analysis_resource_version_language_key
    unique (text_resource_id, analysis_version, native_language);

create index if not exists text_analysis_resource_language_idx
  on public.text_analysis (text_resource_id, native_language);
